import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/redux/provider";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Get Spoused",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/logo_black.svg",
        href: "/logo_black.svg",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="relative h-screen w-full antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
